# Custom Language File for Launcher Customizer

[ejs.app]
title = "HetoniaV2"

[ejs.landing]
mediaGitHubURL = "https://github.com/HetoniaV2/launcher"
mediaTwitterURL = "https://twitter.hetonia.fr/"
mediaInstagramURL = "https://instagram.hetonia.Fr/"
mediaYouTubeURL = "https://youtube.hetonia.fr/"
mediaDiscordURL = "https://dsc.gg/hetonia"

[ejs.settings]
sourceGithubLink = "https://github.com/HetoniaV2/launcher"
supportLink = "https://hetonia.fr/support"

[ejs.welcome]
welcomeHeader = "Rejoignez HetoniaV2 !"
welcomeDescription = "HetoniaV2, Venez d'écouvrire la V2 de Hetonia avec ses ajoutes incroyable, Hétonia est un serveur minecraft de type survie custom et mini-jeux !"
welcomeDescCTA = "Rejoingnez l'aventure !."
