# Custom Language File for Launcher Customizer

[ejs.app]
title = "Hetonia"

[ejs.landing]
mediaGitHubURL = "https://github.com/mc-hetonia/launcher"
mediaTwitterURL = "https://twitter.hetonia.fr/"
mediaInstagramURL = "https://instagram.hetonia.Fr/"
mediaYouTubeURL = "https://youtube.hetonia.fr/"
mediaDiscordURL = "https://discord.gg/hetonia"

[ejs.settings]
sourceGithubLink = "https://github.com/mc-hetonia/launcher"
supportLink = "https://support.hetonia.fr"

[ejs.welcome]
welcomeHeader = "Rejoignez Hetonia !"
welcomeDescription = "Hetonia est un serveur de type Survie Custom avec des dimensions custom et Mini-jeux en version récente mais avec un PvP incroyable !"
welcomeDescCTA = "Lancez-vous dans l'aventure !"
